version: "2.0"

services:
  librespeed:
    image: adolfintel/speedtest
    expose:
      - port: 80
        as: 80
        to:
          - global: true
    env:
      - MODE=standalone
      - TITLE=Librespeed Test
      - WEBPORT=80

deployment:
  librespeed:
    lagrange:
      profile: librespeed
      count: 1
